data_config:
  data_dir: data/raw_train/
  data_prep_dir: prep
  dev_dataset:
    file: merged_sampled.jsonl
    use_weak_label: true
  emb_dir: data/entity_db
  ent_embeddings:
  - args:
      learned_embedding_size: 200
      regularize_mapping: data/raw_train_metadata/qid2reg_pow.csv # COMPUTED IN utils.preprocessing.build_regularization_mapping.py
    cpu: false
    freeze: false
    key: learned
    load_class: LearnedEntityEmb
  - args:
      emb_file: data/raw_train_metadata/static_wiki_0122_title_uncased.pt # COMPUTED IN utils.preprocessing.build_static_embeddings.py
      proj: 256
    cpu: false
    freeze: false
    key: title_static
    load_class: StaticEmb
  - args:
      attn_hidden_size: 128
      max_types: 3
      merge_func: addattn
      type_dim: 128
      type_labels: type_mappings/hyena/qid2typeids.json
      type_vocab: type_mappings/hyena/type_vocab.json
    freeze: false
    key: learned_type
    load_class: LearnedTypeEmb
  - args:
      attn_hidden_size: 128
      max_types: 3
      merge_func: addattn
      type_dim: 128
      type_labels: type_mappings/wiki/qid2typeids.json
      type_vocab: type_mappings/wiki/type_vocab.json
    freeze: false
    key: learned_type_wiki
    load_class: LearnedTypeEmb
  - args:
      attn_hidden_size: 128
      max_types: 50
      merge_func: addattn
      type_dim: 128
      type_labels: type_mappings/relations/qid2typeids.json
      type_vocab: type_mappings/relations/type_vocab.json
    freeze: false
    key: learned_type_relations
    load_class: LearnedTypeEmb
  - args:
      kg_adj: kg_mappings/kg_adj.txt
    batch_on_the_fly: true
    key: adj_index
    load_class: KGIndices
    normalize: false
  entity_dir: data/entity_db
  eval_slices:
  - unif_NS_all
  - unif_NS_HD
  - unif_NS_TO
  - unif_NS_TL
  - unif_NS_TS
  max_aliases: 10
  max_seq_len: 100
  overwrite_preprocessed_data: false
  test_dataset:
    file: merged_sampled.jsonl
    use_weak_label: true
  train_dataset:
    file: train.jsonl
    use_weak_label: true
  train_in_candidates: true
  type_prediction:
    type_labels: type_mappings/hyena_coarse/qid2typeids.json
    type_vocab: type_mappings/hyena_coarse/type_vocab.json
    num_types: 5
    use_type_pred: true
  word_embedding:
    bert_model: bert-base-uncased
    cache_dir: pretrained_bert_models
    freeze: false
    layers: 12
emmental:
  checkpoint_all: true
  checkpoint_freq: 1
  checkpointing: true
  clear_intermediate_checkpoints: false
  distributed_backend: nccl
  evaluation_freq: 0.2
  fp16: true
  grad_clip: 1.0
  l2: 0.01
  log_path: bootleg_logs/wiki_full_ft
  lr: 2e-5
  lr_scheduler: linear
  n_epochs: 3
  warmup_percentage: 0.1
model_config:
  attn_class: BootlegM2E
  ff_inner_size: 1024
  hidden_size: 512
  num_heads: 16
  num_model_stages: 2
run_config:
  dataloader_threads: 1
  dataset_threads: 40
  eval_batch_size: 32
  log_level: debug
  spawn_method: fork
train_config:
  batch_size: 32
