# This file may be used to create an environment using:
# $ conda env create --name <env_name> --file conda_requirements.yml
name: conee_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argh=0.26.2
  - ipdb=0.12.3
  - jsonlines=1.2.0
  - marisa-trie=3.1.1
  - matplotlib=2.2.4
  - mock==3.0.5
  - networkx=2.4
  - nltk=3.4.5
  - notebook=6.0.3
  - numpy=1.17.4
  - pandas=0.25.3
  - pytest=5.3.0
  - python=3.7.3
  - scikit-learn=0.22
  - scipy=1.3.1
  - seaborn=0.9.0
  - tabulate=0.8.7
  - torch=1.6.0
  - tagme=0.1.3
  - tensorboardx=2.0
  - transformers=3.0.1
  - torch=1.6.0
  - torchtext=0.4.0
  - tqdm=4.51.0
  - ujson=1.35
