# This file may be used to create an environment using:
# $ conda env create --name <env_name> --file conda_requirements.yml
name: conee_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipdb=0.12.3
  - jsonlines=1.2.0
  - marisa-trie=0.7.5
  - matplotlib=2.2.4
  - networkx=2.4
  - nltk=3.4.5
  - notebook=6.0.3
  - numpy=1.17.4
  - pytest=5.3.2
  - python=3.6.5
  - torch=1.5.0
  - tagme=0.1.3
  - transformers=3.0.1
  - scikit-learn=0.21.3
  - tensorboardx=2.0
  - termcolor=1.1.0
  - torchtext=0.4.0
  - ujson=1.35
  - tabulate=0.8.7
