name: bootleg-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - marisa-trie=0.7.5
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=21.0
  - python>=3.6
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - appnope==0.1.2
    - argh==0.26.2
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.3
    - blis==0.7.4
    - cachetools==4.2.1
    - catalogue==1.0.0
    - chardet==4.0.0
    - click==7.1.2
    - cymem==2.0.5
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - filelock==3.0.12
    - future==0.18.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.35.0
    - idna==2.10
    - ipdb==0.12.3
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonlines==1.2.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - markdown==3.3.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mock==3.0.5
    - more-itertools==8.6.0
    - murmurhash==1.0.5
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - networkx==2.4
    - nltk==3.4.5
    - notebook>=6.1.5
    - numpy==1.19.5
    - oauthlib==3.1.0
    - packaging==20.8
    - pandas==0.25.3
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plac==1.1.3
    - pluggy==0.13.1
    - preshed==3.0.5
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.14
    - protobuf==3.14.0
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytest==5.3.0
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pyzmq==22.0.0
    - regex==2020.11.13
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - sacremoses==0.0.43
    - scikit-learn==0.22
    - scipy==1.3.3
    - send2trash==1.5.0
    - six==1.15.0
    - spacy==2.3.5
    - srsly==1.0.5
    - tabulate==0.8.7
    - tagme==0.1.3
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.0
    - terminado==0.9.2
    - testpath==0.4.4
    - thinc==7.4.5
    - tokenizers==0.9.4
    - torch==1.7.1
    - torchtext==0.4.0
    - tornado==6.1
    - tqdm==4.51.0
    - traitlets==5.0.5
    - transformers==4.0.0
    - typing-extensions==3.7.4.3
    - ujson==4.0.2
    - urllib3==1.26.3
    - wasabi==0.8.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
