emmental:
  lr: 2e-5
  n_steps: 212439
  evaluation_freq: 35407
  warmup_percentage: 0.1
  lr_scheduler: linear
  log_path: /home/logs/bootleg_uncased_10tokmask
  use_exact_log_path: true
  checkpointing: true
  checkpoint_all: true
  checkpoint_freq: 1
  counter_unit: batch
  online_eval: false
  clear_intermediate_checkpoints: false
  checkpoint_metric: NED/Bootleg/dev/final_loss/acc_boot:max
  l2: 0.01
  grad_clip: 1.0
  gradient_accumulation_steps: 2
  fp16: true
  writer: wandb
  wandb_project_name: platelet
  wandb_run_name: gcp_korealiases_00tokmask
  write_loss_per_step: true
run_config:
  log_level: DEBUG
  eval_batch_size: 16
  dataloader_threads: 3
  dataset_threads: 20
  spawn_method: fork
train_config:
  batch_size: 8
model_config:
  hidden_size: 300
  normalize: true
  temperature: 0.01
data_config:
  data_dir: /home/data/bootleg-data/korealiases_0329
  data_prep_dir: prep
  use_entity_desc: true
  context_mask_perc: 0.1
  entity_type_data:
    use_entity_types: true
    type_symbols_dir: type_mappings/wiki
  entity_kg_data:
    use_entity_kg: true
    kg_symbols_dir: kg_mappings
  entity_dir: /home/data/bootleg-data/korealiases_0329/entity_db
  max_seq_len: 128
  max_seq_window_len: 64
  max_ent_len: 128
  overwrite_preprocessed_data: false
  dev_dataset:
    file: dev.jsonl
    use_weak_label: true
  test_dataset:
    file: test.jsonl
    use_weak_label: true
  train_dataset:
    file: train.jsonl
    use_weak_label: true
  train_in_candidates: true
  eval_slices:
    - unif_all
    - unif_NS_all
    - unif_HD
    - unif_TO
    - unif_TL
    - unif_TS
  word_embedding:
    cache_dir: /home/data/bootleg-archive/pretrained_bert_models
    bert_model: bert-base-uncased
    context_layers: 6
    entity_layers: 6
