emmental:
  lr: 2e-5
  n_epochs: 10
  evaluation_freq: 220000
  checkpoint_freq: 1
  counter_unit: batch
  checkpoint_all: true
  clear_intermediate_checkpoints: false
  lr_scheduler: linear
  grad_clip: 1.0
  warmup_percentage: 0.1
  l2: 0.01
  log_path: /data/logs
  device: 0
run_config:
  eval_batch_size: 16
  dataset_threads: 8
  mp_sharing_strategy: file_system
  log_level: info
  dataloader_threads: 0
train_config:
  batch_size: 16
model_config:
  hidden_size: 128
data_config:
  data_dir: /data/output/full_wiki_0_-1_final
  data_prep_dir: prep
  entity_dir: /data/output/full_wiki_0_-1_final/entity_db
  overwrite_preprocessed_data: false
  use_entity_desc: false
  entity_type_data:
    use_entity_types: true
  entity_kg_data:
    use_entity_kg: true
  max_seq_len: 64
  max_seq_window_len: 32
  max_ent_len: 64
  dev_dataset:
    file: dev.jsonl
    use_weak_label: false
  test_dataset:
    file: test.jsonl
    use_weak_label: false
  train_dataset:
    file: train.jsonl
    use_weak_label: false
  train_in_candidates: true
  word_embedding:
    bert_model: avichr/heBERT
    cache_dir: /data/bert_cache
    context_layers: 6
    entity_layers: 6
